### PR TITLE
Small but useful changes

### PR DESCRIPTION
**Pull request by andrzejQ**
I've added small but useful changes, such as suggesting a name when writing to HTML, and filtering before displaying with regular expressions. I have no experience with C#, so you can close this pull request without an answer.

### CODE REVIEW

**Comment by andrzejQ** [comment]
Newer v. RegExp 0.6.2.1

**Comment by andrzejQ** [comment]
There are differences - so I do not understand "no conflicts"...

**Comment by mohzy83** [comment]
Unfortunately, this PR is not compatible with the current master.
Therefore I am going to close this one.

### already implemented in master:
- Save As UTF-8
- MarkdownPreviewForm.cs: </html> at the end, no </meta>

### known issus:
- Link handling (solution in this PR doesn't work anymore, cause markdig is used as external lib)
- auto save is not implemented yet

### not clear
- why was the regexp handling implemented?

**Comment by andrzejQ** [comment]
> Unfortunately, this PR is not compatible with the current master. Therefore I am going to close this one.
Ok.
> 
> ### not clear
> 
> * why was the regexp handling implemented?

Pre-converting text using RegExp allows "non-standard" Markdown expressions to be displayed correctly, e.g. `{style}` instead of `{:style}` _(Jekyll)_.

**Pull request closed without merging**
